apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: "monihub/front-end:1.0.1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: NODE_ENV
            value: "production"
          - name: BROKER_URL
            value: "http://broker-service.info"
        ports:
          - containerPort: 8081
        volumeMounts:
          - name: nextjs-storage
            mountPath: /app/.next
      volumes:
        - name: nextjs-storage
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  selector:
    app: front-end
  ports:
    - protocol: TCP
      name: main-port
      port: 8081
      targetPort: 8081
  type: LoadBalancer  # Use LoadBalancer for cloud deployments or NodePort for local
